### ISSUE TITLE
No migw64-w64 library found in Ubuntu

### ISSUE THREAD

**Issue by manu1022** [clarive/clax#8]
In the README file there are two things to improve:

In Debian, this libraries does not exists

`apt-get install migw64-w64`

You need to install this one:

`apt-get install mingw-w64`

Also, add to the README doc that you need libtoolize, m4 and automake libraries

**Comment by vti** [comment]
> Also, add to your doc that you need libtoolize, m4 and automake libraries

This is already in README https://github.com/clarive/clax/tree/libuv#compiling-testing-and-installing

**Comment by manu1022** [comment]
I need also libtoolize and m4 libraries

![image](https://user-images.githubusercontent.com/5825483/34768377-f572ea3c-f5fa-11e7-8986-250e2b9d5310.png)

**Comment by vti** [comment]
It comes with `libtool`.
