### ISSUE TITLE
Clax log in windows always load in C:/

### ISSUE THREAD

**Issue by manu1022** [clarive/clax#9]
INI file:

```
[bind]
host = 0.0.0.0
port = 11801

#root = C:\Users\clarive\Clax\
#chdir = yes
log_file = C:\Users\clarive\Clax\clax.log
```

Clax always dumps log into C:\clax.log

**Comment by vti** [comment]
Log file has to be specified as a command line argument. Configuring it through the config file is not supported (and wasn't). I have cleaned up config examples.

**Comment by manu1022** [comment]
Still happens with clax as a windows service:

![image](https://user-images.githubusercontent.com/5825483/36372804-734a5f5a-1566-11e8-9df0-a5fa61a015ca.png)

![image](https://user-images.githubusercontent.com/5825483/36372818-7f6c2926-1566-11e8-8be1-3dc4076aa08b.png)

**Comment by vti** [comment]
Try now.

**Comment by manu1022** [comment]
Solved
